name: Create torrent using torrenttools
on:
  push:
    paths:
      - ".github/workflows/torrenttools.yml"
      
env:
  name: "gpt3 neo"
  comment: "doing"
  url: "https://the-eye.eu/public/AI/gptneo-release/GPT3_2-7B/"
  file_name: "gpt 3 neo"
  piece_size: auto # auto for automatic calculation, or use the recommended piece size on the README.md file
  protocol_version: 1 # BitTorrent version 1, 2, or hybrid
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install torrenttools
        run: |
          sudo add-apt-repository ppa:fbdtemme/torrenttools
          sudo apt-get update
          sudo apt-get install torrenttools
          
      - name: Download file
        run: wget -m -np -c -U "eye02" -w 2 -R "index.html*" "$url" -O "$file_name"
        
      - name: Create torrent using torrenttools
        run: torrenttools create -v $protocol_version -o "${name}.torrent" -w "$url" -c "$comment" -l $piece_size "$file_name" # Tested on v0.4.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
